[package]
name = "frontend"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mytodo = { path = ".." }
futures = "^0.1.28"
seed = "^0.4.1"
wasm-bindgen = "^0.2.50"
web-sys = "^0.3.27"
